<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class SaveProjectRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
        //aceder al usuario
//        $this->user()->isAdmin();
    }

    /**
     * Get the validation rules that apply to the request.
     *pasa al emtodo rules despues de validar el usuario
     * @return array
     */
    public function rules()
    {
        return [
            //
            'title'=>'required',
            'url'=>'required',
            'description'=>'required'
        ];
    }
    /*modificar los mensajes de error del reuest
    */
    public function messages()
    {
       // return parent::messages(); // TODO: Change the autogenerated stub
        return[
          'title.required'=>'El proyecto necesita un titulo'
        ];
    }
}
